#!/usr/bin/env python3
"""Fail a pull request that changes a generated review report (issue #235).

    python .github/scripts/check_generated_reports.py --base <base sha> --head <PR head sha>

data/clubs-review.json and data/schools-review.json are written by every publishing build, and the
daily refresh commits them to main. A PR that commits its own copy conflicts with the next refresh
that lands while it is in review (PR #234 did). So only the refresh commits them, and this check
keeps PRs from doing so.

What is compared
----------------
The PR head against its merge base with the base branch: `git diff --name-only <merge-base> <head>`.
That is exactly what the PR changes (its "Files changed" tab), and exactly what conflicts.

  * Not the checked-out HEAD. In the pull_request job the checkout is GitHub's test merge
    (refs/pull/N/merge), which carries every report change main made since the branch was cut, so
    diffing it would fail every PR cut before a refresh. The script only ever diffs the --head
    value it is given; tests/generated_reports_check_test.py runs it with such a merge checked out.
  * Not main's current tip. A branch cut before a refresh that copies main's CURRENT report still
    changes the file against its merge base, and still conflicts at the next refresh; a diff
    against the tip would miss it (the false pass from the #235 plan review).

`--name-only` compares tree entries only, so a `filter: blob:none` checkout never has to fetch the
report blobs. Offline: no API calls, no network.

Exit status: 0 when neither report changes, 1 when one does (the message says how to undo it), 2 on
bad input (an unknown sha, or no merge base).
"""
from __future__ import annotations

import argparse
import os
import subprocess
import sys

REPORTS = ("data/clubs-review.json", "data/schools-review.json")

FIX = ('git fetch origin main && git checkout "$(git merge-base HEAD origin/main)" -- '
       + " ".join(REPORTS) + ' && git commit -m "Drop generated review reports"')


def git(repo: str, *args: str) -> subprocess.CompletedProcess:
    return subprocess.run(["git", "-C", repo, *args], capture_output=True, text=True)


def changed_reports(repo: str, base: str, head: str) -> list[str]:
    """The reports `head` changes relative to its merge base with `base`. Raises ValueError on bad input."""
    for sha in (base, head):
        if git(repo, "rev-parse", "--verify", "--quiet", sha + "^{commit}").returncode != 0:
            raise ValueError(f"{sha} is not a commit in this checkout (is the history complete? fetch-depth: 0)")
    mb = git(repo, "merge-base", base, head)
    if mb.returncode != 0 or not mb.stdout.strip():
        raise ValueError(f"{base} and {head} have no merge base")
    diff = git(repo, "diff", "--name-only", "--no-renames", mb.stdout.strip(), head, "--", *REPORTS)
    if diff.returncode != 0:
        raise ValueError(f"git diff failed: {diff.stderr.strip()}")
    return [p for p in diff.stdout.splitlines() if p]


def message(changed: list[str]) -> str:
    return "\n".join([
        f"This pull request changes {', '.join(changed)}.",
        "These review reports are generated by the build and published to main by the daily refresh "
        "(issue #235). A PR that commits them conflicts with the next refresh that lands while it is in review.",
        "Put back the copy your branch started from (works whether or not you rebased):",
        f"    {FIX}",
        "To show a table edit's effect in the PR description instead: python tools/clubs_review.py --dry-run --top 20 "
        "(or tools/schools_review.py).",
    ])


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--base", required=True, help="the base branch's sha (github.event.pull_request.base.sha)")
    ap.add_argument("--head", required=True, help="the PR head's sha (github.event.pull_request.head.sha)")
    ap.add_argument("--repo", default=os.getcwd(), help=argparse.SUPPRESS)
    args = ap.parse_args(argv)
    try:
        changed = changed_reports(args.repo, args.base, args.head)
    except ValueError as e:
        print(f"::error title=generated reports::{e}")
        return 2
    if changed:
        text = message(changed)
        print("::error title=generated reports::" + text.replace("\n", "%0A"))
        print(text)
        return 1
    print(f"ok: the PR changes neither {' nor '.join(REPORTS)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
