// The human review sheet for the recommender's held-out scenarios (issue #400, plan §5: "the owner reviews the
// reasons on the held-out top 10s by hand"). Offline: it reads the frozen catalog and the scenarios, ranks each
// held-out scenario with public/recs.js, and writes docs/recs-heldout-review.md.
//
//     node tools/recs_review_sheet.mjs           # write the sheet
//     node tools/recs_review_sheet.mjs --check   # exit 1 if the committed sheet is not what the code gives now
//
// tests/recs_review_sheet.test.mjs runs --check, so a change to the ranker or its words that alters what a reviewer
// would read can't land without the sheet being regenerated (and so re-reviewed). Programs and schools only.
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const R = createRequire(import.meta.url)(path.join(ROOT, 'public', 'recs.js'));
const OUT = path.join(ROOT, 'docs', 'recs-heldout-review.md');
const read = (p) => JSON.parse(readFileSync(path.join(ROOT, p), 'utf8'));

const WORDS = { lt5k: 'under 5,000', '5k-15k': '5,000–14,999', ge15k: '15,000+', mild: 'mild winters', 'four-season': 'four seasons', cold: 'cold winters' };
const LEGEND = { region: 'Region', division: 'Division', size: 'School size', climate: 'Climate' };
const prefsText = (p) => Object.keys(LEGEND).filter((c) => p[c] && p[c].mode !== 'skip')
  .map((c) => `${LEGEND[c]}: ${p[c].values.map((v) => WORDS[v] || v).join(' or ')} (${p[c].mode === 'must' ? 'must have' : 'prefer'})`).join(' · ');
const filterText = (f) => [['conf', 'Conference'], ['region', 'Region'], ['division', 'Division']]
  .filter(([k]) => f[k]?.length).map(([k, l]) => `${l} = ${f[k].join(' or ')}`).join(' · ') || 'none';
const predicate = (f) => (r) => (!f.conf?.length || f.conf.includes(r.conference)) && (!f.region?.length || f.region.includes(r.region))
  && (!f.division?.length || f.division.includes(r.division));
const cell = (s) => String(s).replace(/\|/g, '\\|');

export function sheet() {
  const cat = read('tests/fixtures/recs/catalog.json');
  const sc = read('tests/fixtures/recs/scenarios.json');
  const list = { updated: cat.updated, programs: cat.programs };
  const fit = { updated: cat.updated, fitTaxonomy: cat.fitTaxonomy, constants: cat.constants, sources: cat.sources, fit: cat.fit };
  const bySlug = new Map(cat.programs.map((p) => [p.slug, p]));
  const out = [
    '# Recommendations: held-out review sheet',
    '',
    `Issue #400, PR 7. Generated by \`tools/recs_review_sheet.mjs\` from the frozen catalog (${cat.updated}, taxonomy ${cat.fitTaxonomy}, ranker ${R.RANKER}); do not edit by hand.`,
    '',
    'For each held-out scenario: the preferences, the counts, and the top 10 confirmed programs with every reason, tradeoff and unknown exactly as a card shows them. **Reviewer:** tick each box only if it holds for all ten rows, and note any row that reads wrong.',
    '',
    'Check each scenario for:',
    '- every ✓ reason is true of that program and names where it came from;',
    '- the ↔ tradeoff names a real miss against a stated preference, and nothing else;',
    '- every ? unknown is a real gap, and is never presented as a match or a miss;',
    '- the order follows the plan: more matched preferences first, then the displayed name;',
    '- nothing reads as an admission, recruiting or "fit" claim.',
    '',
  ];
  for (const s of sc.scenarios.filter((x) => x.split === 'heldout')) {
    const res = R.rank({ list, fit, prefs: s.prefs, filter: predicate(s.filters || {}), hidden: s.hidden || [] });
    const ex = res.excluded;
    out.push(`## ${s.id}`, '', `*${s.why}*`, '',
      `- **Preferences:** ${prefsText(res.prefs)}`,
      `- **Filters:** ${filterText(s.filters || {})}${s.hidden?.length ? ` · **Hidden:** ${s.hidden.join(', ')}` : ''}`,
      `- **Result:** ${res.confirmed.length} confirmed · ${res.needVerification.length} need verification · filtered out ${ex.byFilter} · ruled out by must-haves ${ex.byMustHave} · hidden ${ex.hidden}${res.staleHidden.length ? ` · no longer listed: ${res.staleHidden.join(', ')}` : ''}`,
      '');
    if (res.confirmed.length) {
      out.push('| # | Program | Line | Matched | Reasons | Tradeoff | Unknowns |', '|---|---|---|---|---|---|---|');
      res.confirmed.slice(0, 10).forEach((it, i) => {
        const p = bySlug.get(it.slug);
        out.push(`| ${i + 1} | ${cell(it.displayName)} | ${cell([p.division, p.conference, p.state].filter(Boolean).join(' · '))} | ${it.matched} of ${it.of} | `
          + `${cell(it.reasons.map((r) => `✓ ${R.reasonText(r)}`).join('<br>') || '—')} | ${cell(it.tradeoff ? `↔ ${R.tradeoffText(it.tradeoff)}` : '—')} | `
          + `${cell(it.unknowns.map((u) => `? ${R.unknownText(u)}`).join('<br>') || '—')} |`);
      });
      out.push('');
    }
    if (res.needVerification.length) out.push(`**Need verification:** ${res.needVerification.map((it) => `${it.displayName} (${it.unknowns.map((u) => R.unknownText(u)).join('; ')})`).join(' · ')}`, '');
    out.push('- [ ] Reasons true and sourced', '- [ ] Tradeoffs and unknowns honest', '- [ ] Order sensible', '- [ ] No admission, recruiting or fit claim', '- Notes:', '');
  }
  return out.join('\n');
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  const text = sheet();
  if (process.argv.includes('--check')) {
    let now = '';
    try { now = readFileSync(OUT, 'utf8').replace(/\r\n/g, '\n'); } catch { /* missing */ }
    const same = now === text;
    console.log(same ? 'recs review sheet: current' : 'recs review sheet: OUT OF DATE - run node tools/recs_review_sheet.mjs');
    process.exit(same ? 0 : 1);
  }
  writeFileSync(OUT, text);
  console.log(`wrote ${path.relative(ROOT, OUT)}`);
}
